### ISSUE TITLE
Request: Simple dynamic speed playback

### ISSUE THREAD

**Issue by IkkAlpha** [TinosNitso/mpv-scripts#1]
There are two ways, 
the first, increase speed gradually over a set period of time
For example, over 20 minutes I would like the speed to become x3, it would increase the speed +0.15 every minute,
It would be even better if it could increase in 0.01 or even smaller increments every second over the set period of time, but if this is too complicated then the older method is better.

Second, percentage of playback time remaining smoothed playback dynamic acceleration 
1- set desired speed *e.g. x3
2- select starting speed *e.g. x1.5
3- % of video passed until desired speed is reached e.g. *60%
Result:
The video begins at x1.5, increases gradually as a function of time based on elapsed % of playback
by 60%, speed had gradually increased from 1.5x to 3x in 0.01 (or calculated) stepsizes.
at 60% of elapsed video duration it will be
playbackRate = x1.5 + (x3 - x1.5) * (currentTime / duration) / 0.6
This formula means that the playback rate will start at x1.5 and increase linearly as a function of the current time divided by the duration of the video until it reaches 60% of the duration, where it will reach x3.

**Comment by TinosNitso** [comment]
I never thought of this! Unfortunately this probably won't make it into the next release, but probably afterwards. I need to urgently optimize one of the other scripts (too much CPU usage). The mask was never filtering colors properly, but now that's using too much CPU! 😔 

The controller can set its own speed using a new option (maybe `o.speed_expr`), expressed as string. It can gsub `time-pos` & `duration` & then apply formula every half a second (maybe `loadstring`). I was thinking of doing a smooth toggle fade, but your request is easier to code!

**Comment by TinosNitso** [comment]
I haven't released it yet but I just added `o.speed_expr` & `o.suppress_osd` to resolve this issue. Let me know if it works for you! Uses loadstring return expand-text for arbitrary formulas. [aspeed.lua](https://github.com/TinosNitso/mpv-scripts/blob/main/aspeed.lua)

**Comment by TinosNitso** [comment]
In release v1.5.4, set options:
`speed = 'clip(1.5+(3-1.5)*${percent-pos}/60,1.5,3)'`
`suppress_osd = false`
There's also a random walker example you might like to try. 🙂

Let me know if there's anything else missing!  v1.5.4 also adds first-child feedback.
